title: Rimvydas Rubavičius
position: Ph.D. Student
affiliation: The University of Edinburgh
email: rimvydas.rubavicius (at) ed.ac.uk
keywords: Interactive Task Learning Robotics Reasoning Planning Natural Language Processing
google_scholar: https://scholar.google.com/citations?user=7rA4ov4AAAAJ&hl 
github_link: https://github.com/rimvydasrub
linkedin: https://www.linkedin.com/rimvydasrub
twitter: https://twitter.com/rimvydasrub
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Rimvydas Rubavicius Homepage
